# Generated by Django 3.2.25 on 2025-04-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
